In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [2]:
data_df=pd.read_csv('NFA 2019 public_data.csv')
data_df

,country,year,country_code,record,crop_land,grazing_land,forest_land,fishing_ground,built_up_land,carbon,total,QScore
0,Armenia,1992,1,AreaPerCap,1.402924e-01,1.995463e-01,0.097188051,3.688847e-02,2.931995e-02,0.000000e+00,5.032351e-01,3A
1,Armenia,1992,1,AreaTotHA,4.830000e+05,6.870000e+05,334600,1.270000e+05,1.009430e+05,0.000000e+00,1.732543e+06,3A
2,Armenia,1992,1,BiocapPerCap,1.598044e-01,1.352610e-01,0.084003213,1.374213e-02,3.339780e-02,0.000000e+00,4.262086e-01,3A
3,Armenia,1992,1,BiocapTotGHA,5.501762e+05,4.656780e+05,289207.1078,4.731155e+04,1.149823e+05,0.000000e+00,1.467355e+06,3A
4,Armenia,1992,1,EFConsPerCap,3.875102e-01,1.894622e-01,1.26E-06,4.164833e-03,3.339780e-02,1.114093e+00,1.728629e+00,3A
...,...,...,...,...,...,...,...,...,...,...,...,...
72181,World,2016,5001,BiocapTotGHA,3.984702e+09,1.504757e+09,5.11176e+09,1.095445e+09,4.726163e+08,0.000000e+00,1.216928e+10,3A
72182,World,2016,5001,EFConsPerCap,5.336445e-01,1.402092e-01,0.273495,8.974253e-02,6.329435e-02,1.646235e+00,2.746619e+00,3A
72183,World,2016,5001,EFConsTotGHA,3.984702e+09,1.046937e+09,2.04218e+09,6.701039e+08,4.726163e+08,1.229237e+10,2.050891e+10,3A
72184,World,2016,5001,EFProdPerCap,5.336445e-01,1.402092e-01,0.273495,8.974253e-02,6.329435e-02,1.646235e+00,2.746619e+00,3A
72185,World,2016,5001,EFProdTotGHA,3.984702e+09,1.046937e+09,2.04218e+09,6.701039e+08,4.726163e+08,1.229237e+10,2.050891e+10,3A

In [3]:
data_df.isnull().sum()

country               0
year                  0
country_code          0
record                0
crop_land         20472
grazing_land      20472
forest_land       20472
fishing_ground    20473
built_up_land     20473
carbon            20473
total                 9
QScore                1
dtype: int64

In [4]:
data_df.head()

,country,year,country_code,record,crop_land,grazing_land,forest_land,fishing_ground,built_up_land,carbon,total,QScore
0,Armenia,1992,1,AreaPerCap,0.140292,0.199546,0.097188051,0.036888,0.029320,0.000000,5.032351e-01,3A
1,Armenia,1992,1,AreaTotHA,483000.000000,687000.000000,334600,127000.000000,100943.000800,0.000000,1.732543e+06,3A
2,Armenia,1992,1,BiocapPerCap,0.159804,0.135261,0.084003213,0.013742,0.033398,0.000000,4.262086e-01,3A
3,Armenia,1992,1,BiocapTotGHA,550176.242700,465677.972200,289207.1078,47311.551720,114982.279300,0.000000,1.467355e+06,3A
4,Armenia,1992,1,EFConsPerCap,0.387510,0.189462,1.26E-06,0.004165,0.033398,1.114093,1.728629e+00,3A

In [5]:
data_df['QScore'].value_counts()

3A    51481
2A    10576
2B    10096
1A       16
1B       16
Name: QScore, dtype: int64

In [6]:
data_df.isna().sum()

country               0
year                  0
country_code          0
record                0
crop_land         20472
grazing_land      20472
forest_land       20472
fishing_ground    20473
built_up_land     20473
carbon            20473
total                 9
QScore                1
dtype: int64

In [7]:
#for simplicity,we drop the row with missing values.
df=data_df.dropna()
df

,country,year,country_code,record,crop_land,grazing_land,forest_land,fishing_ground,built_up_land,carbon,total,QScore
0,Armenia,1992,1,AreaPerCap,1.402924e-01,1.995463e-01,0.097188051,3.688847e-02,2.931995e-02,0.000000e+00,5.032351e-01,3A
1,Armenia,1992,1,AreaTotHA,4.830000e+05,6.870000e+05,334600,1.270000e+05,1.009430e+05,0.000000e+00,1.732543e+06,3A
2,Armenia,1992,1,BiocapPerCap,1.598044e-01,1.352610e-01,0.084003213,1.374213e-02,3.339780e-02,0.000000e+00,4.262086e-01,3A
3,Armenia,1992,1,BiocapTotGHA,5.501762e+05,4.656780e+05,289207.1078,4.731155e+04,1.149823e+05,0.000000e+00,1.467355e+06,3A
4,Armenia,1992,1,EFConsPerCap,3.875102e-01,1.894622e-01,1.26E-06,4.164833e-03,3.339780e-02,1.114093e+00,1.728629e+00,3A
...,...,...,...,...,...,...,...,...,...,...,...,...
72181,World,2016,5001,BiocapTotGHA,3.984702e+09,1.504757e+09,5.11176e+09,1.095445e+09,4.726163e+08,0.000000e+00,1.216928e+10,3A
72182,World,2016,5001,EFConsPerCap,5.336445e-01,1.402092e-01,0.273495,8.974253e-02,6.329435e-02,1.646235e+00,2.746619e+00,3A
72183,World,2016,5001,EFConsTotGHA,3.984702e+09,1.046937e+09,2.04218e+09,6.701039e+08,4.726163e+08,1.229237e+10,2.050891e+10,3A
72184,World,2016,5001,EFProdPerCap,5.336445e-01,1.402092e-01,0.273495,8.974253e-02,6.329435e-02,1.646235e+00,2.746619e+00,3A
72185,World,2016,5001,EFProdTotGHA,3.984702e+09,1.046937e+09,2.04218e+09,6.701039e+08,4.726163e+08,1.229237e+10,2.050891e+10,3A

In [8]:
df.isnull().sum()

country           0
year              0
country_code      0
record            0
crop_land         0
grazing_land      0
forest_land       0
fishing_ground    0
built_up_land     0
carbon            0
total             0
QScore            0
dtype: int64

In [9]:
#for now we will convert this to a binary classificationproblem by combining class '2A' and '1A'
df['QScore']=df['QScore'].replace(['1A'], '2A')
df.QScore.value_counts()

3A    51473
2A      240
Name: QScore, dtype: int64

In [10]:
df_2A=df[df.QScore=='2A']
df_3A=df[df.QScore=='3A'].sample(350)
data_df=df_2A.append(df_3A)
data_df

,country,year,country_code,record,crop_land,grazing_land,forest_land,fishing_ground,built_up_land,carbon,total,QScore
1536,Algeria,2016,4,AreaPerCap,2.072989e-01,8.112722e-01,0.048357265,2.258528e-02,2.998367e-02,0.000000,1.119497e+00,2A
1537,Algeria,2016,4,AreaTotHA,8.417600e+06,3.294260e+07,1963600,9.171000e+05,1.217520e+06,0.000000,4.545842e+07,2A
1538,Algeria,2016,4,BiocapPerCap,2.021916e-01,2.636077e-01,0.027166736,7.947991e-03,2.924496e-02,0.000000,5.301590e-01,2A
1539,Algeria,2016,4,BiocapTotGHA,8.210214e+06,1.070408e+07,1103135.245,3.227369e+05,1.187524e+06,0.000000,2.152769e+07,2A
1540,Algeria,2016,4,EFConsPerCap,6.280528e-01,1.810332e-01,0.162800822,1.472910e-02,2.924496e-02,1.391455,2.407316e+00,2A
...,...,...,...,...,...,...,...,...,...,...,...,...
53000,Rwanda,1978,184,EFProdPerCap,4.237266e-01,1.166016e-01,0.449600575,2.357850e-04,3.467844e-02,0.021367,1.046210e+00,3A
71371,China,1971,351,AreaTotHA,1.021650e+08,2.780000e+08,1.80743e+08,1.352270e+08,1.919830e+07,0.000000,7.153336e+08,3A
6080,Bolivia,1988,19,AreaPerCap,3.412819e-01,5.005468e+00,9.528577578,2.317683e-01,4.256847e-02,0.000000,1.514966e+01,3A
34819,"Korea, Republic of",1999,117,BiocapTotGHA,8.530342e+06,4.293478e+04,4716291.192,1.994133e+07,3.115906e+06,0.000000,3.634680e+07,3A
59980,Syrian Arab Republic,1982,212,BiocapPerCap,5.665745e-01,2.378379e-01,0.075060809,8.303431e-03,2.716803e-02,0.000000,9.149446e-01,3A

In [11]:

import sklearn.utils
data_df=sklearn.utils.shuffle(data_df)
data_df=data_df.reset_index(drop=True)
data_df.shape

(590, 12)

In [12]:
data_df.QScore.value_counts()

3A    350
2A    240
Name: QScore, dtype: int64

In [13]:
#more preprocessing
data_df=data_df.drop(columns=['country_code', 'country' , 'year'])
x=data_df.drop(columns='QScore')
y=data_df['QScore']

In [14]:
print(x,y)

           record     crop_land  grazing_land  forest_land  fishing_ground  \
0    EFProdTotGHA  4.221511e+06  3.384675e+05  3794610.736    5.503842e+04
1    EFProdPerCap  3.503465e-01  1.785289e-01  0.688102496    1.471707e-02
2    EFProdPerCap  3.878852e-02  1.080633e+00  0.160610252    1.064860e-04
3    EFProdTotGHA  4.122713e+06  7.519737e+05  656933.4376    2.468718e+06
4      AreaPerCap  2.122392e-03  1.804033e+00  0.005942697    2.446057e-01
..            ...           ...           ...          ...             ...
585    AreaPerCap  1.745976e-01  2.810378e-02  0.008998831    4.078589e-02
586  EFProdTotGHA  4.377869e+06  5.594718e+05  4047211.471    3.772617e+05
587     AreaTotHA  5.672000e+06  8.541000e+06  351247.9339    2.369000e+05
588    AreaPerCap  1.229292e-01  1.608370e-01  0.097250986    3.881948e-01
589  BiocapTotGHA  4.125401e+07  7.060498e+05  2453017.502    6.500436e+06

     built_up_land        carbon         total
0     8.222577e+05  5.506286e+05  9.782514e+06
1     2.460345e-02  5.507593e-02  1.311374e+00
2     1.609432e-02  9.081539e-01  2.204387e+00
3     1.417287e+06  6.299354e+07  7.241116e+07
4     2.647769e-02  0.000000e+00  2.083182e+00
..             ...           ...           ...
585   2.330287e-02  0.000000e+00  2.757889e-01
586   3.375165e+05  5.350974e+05  1.023443e+07
587   2.260860e+05  0.000000e+00  1.502723e+07
588   2.028078e-02  0.000000e+00  7.894928e-01
589   3.918551e+06  0.000000e+00  5.483207e+07

[590 rows x 8 columns] 0      3A
1      3A
2      3A
3      3A
4      2A
       ..
585    3A
586    3A
587    3A
588    3A
589    3A
Name: QScore, Length: 590, dtype: object

In [15]:

#splir the data into training and testing sets
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.3, random_state=0)
y_train.value_counts()

3A    255
2A    158
Name: QScore, dtype: int64

In [16]:
#there are still imbalance in the class distribution.For this ,we will use SMOTE only on the training data to handle this
#encode categorical variable
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
x_train.record=encoder.fit_transform(x_train.record)
x_test.record=encoder.transform(x_test.record)
x_train

,record,crop_land,grazing_land,forest_land,fishing_ground,built_up_land,carbon,total
285,2,9.140566e-02,6.791892e-02,82.59086827,1.435518e+01,5.091948e-03,0.000000e+00,9.711047e+01
113,2,5.736778e-01,7.396747e-01,0.495167002,1.466589e+00,9.803011e-02,0.000000e+00,3.373139e+00
18,6,4.533118e-01,1.466440e-01,0.49383237,2.673793e-02,9.023299e-02,3.580372e-01,1.568796e+00
76,1,2.150000e+05,2.290000e+05,334820,1.356100e+06,6.290070e+04,0.000000e+00,2.197821e+06
206,3,5.237813e+07,6.391183e+06,41965084.72,3.221363e+06,1.517000e+06,0.000000e+00,1.054728e+08
...,...,...,...,...,...,...,...,...
277,5,6.712415e+06,8.396867e+05,7381727.027,8.694226e+05,1.352299e+06,5.796487e+06,2.295204e+07
9,3,5.964131e+06,3.720434e+04,5606790.384,2.363113e+06,1.384345e+06,0.000000e+00,1.535558e+07
359,0,2.117565e-01,9.747266e-02,0.034947909,3.475393e-02,2.452852e-02,0.000000e+00,4.034595e-01
192,7,3.885366e+05,3.673652e+03,1923548.003,1.574918e+06,1.467565e+05,7.384533e+04,4.111278e+06
559,0,2.301621e-01,1.498663e+00,0.164972195,2.965179e-01,2.801332e-02,0.000000e+00,2.218328e+00

In [17]:
import imblearn
from imblearn.over_sampling import SMOTE
smote=SMOTE(random_state=1)
x_train_balance,y_balance=smote.fit_sample(x_train,y_train)

In [18]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
normalised_train_df=scaler.fit_transform(x_train_balance.drop(columns=['record']))
normalised_train_df

array([[3.14588796e-11, 4.53632023e-11, 1.54100163e-08, ...,
        2.03302646e-11, 0.00000000e+00, 6.82848983e-09],
       [2.01387037e-10, 4.94030389e-10, 9.19577658e-11, ...,
        3.91397975e-10, 0.00000000e+00, 2.22742544e-10],
       [1.58976205e-10, 9.79438894e-11, 9.17087397e-11, ...,
        3.60266963e-10, 4.67964268e-11, 9.55890218e-11],
       ...,
       [2.17572059e-10, 5.60228612e-11, 1.56038038e-11, ...,
        2.91644567e-10, 2.81705729e-10, 2.06693768e-10],
       [8.68635765e-04, 2.08210231e-02, 7.87167130e-04, ...,
        1.45167733e-03, 0.00000000e+00, 2.83622107e-03],
       [3.12546607e-11, 1.60087712e-11, 4.60794586e-11, ...,
        6.02427870e-11, 0.00000000e+00, 9.38611330e-11]])

In [19]:
normalised_train_df=pd.DataFrame(normalised_train_df,columns=x_train_balance.drop(columns=['record']).columns)
normalised_train_df['record']=x_train_balance['record']
normalised_train_df

,crop_land,grazing_land,forest_land,fishing_ground,built_up_land,carbon,total,record
0,3.145888e-11,4.536320e-11,1.541002e-08,1.298299e-08,2.033026e-11,0.000000e+00,6.828490e-09,2
1,2.013870e-10,4.940304e-10,9.195777e-11,1.326400e-09,3.913980e-10,0.000000e+00,2.227425e-10,2
2,1.589762e-10,9.794389e-11,9.170874e-11,2.418208e-11,3.602670e-10,4.679643e-11,9.558902e-11,6
3,7.575506e-05,1.529496e-04,6.247334e-05,1.226472e-03,2.511392e-04,0.000000e+00,1.548822e-04,1
4,1.845539e-02,4.268685e-03,7.830174e-03,2.913437e-03,6.056820e-03,0.000000e+00,7.432753e-03,3
...,...,...,...,...,...,...,...,...
505,1.612806e-04,1.283458e-03,5.235785e-04,2.375105e-04,5.709101e-04,0.000000e+00,3.940044e-04,1
506,7.416216e-05,4.666912e-05,8.742596e-05,9.299755e-04,1.658287e-04,3.506168e-06,1.300560e-04,3
507,2.175721e-10,5.602286e-11,1.560380e-11,1.153972e-10,2.916446e-10,2.817057e-10,2.066938e-10,4
508,8.686358e-04,2.082102e-02,7.871671e-04,1.831771e-03,1.451677e-03,0.000000e+00,2.836221e-03,1
509,3.125466e-11,1.600877e-11,4.607946e-11,1.053736e-09,6.024279e-11,0.000000e+00,9.386113e-11,2

In [20]:
x_test= x_test.reset_index(drop=True)
normalised_test_df= scaler.transform(x_test.drop(columns=['record']))
normalised_test_df= pd.DataFrame(normalised_test_df, columns=x_test.drop(columns=['record']).columns)
normalised_test_df['record']=x_test['record']
normalised_test_df

,crop_land,grazing_land,forest_land,fishing_ground,built_up_land,carbon,total,record
0,3.445974e-03,1.335805e-02,3.541309e-04,2.713233e-05,8.150595e-04,0.000000e+00,2.248870e-03,1
1,1.074658e-10,3.449890e-09,2.791670e-11,2.598518e-12,2.377307e-10,2.594987e-10,5.256978e-10,4
2,3.962763e-03,7.145095e-03,6.470667e-04,6.681531e-04,6.131611e-03,0.000000e+00,1.951119e-03,3
3,1.589762e-10,9.794389e-11,5.478635e-11,3.897060e-11,3.602670e-10,0.000000e+00,5.756524e-11,2
4,1.194978e-04,4.259465e-04,1.238176e-05,5.345225e-06,3.787409e-04,0.000000e+00,8.061951e-05,3
...,...,...,...,...,...,...,...,...
172,1.506395e-10,1.109974e-10,1.582226e-10,3.533702e-11,4.074139e-10,0.000000e+00,9.689017e-11,2
173,6.986209e-11,9.188128e-11,4.504959e-12,5.978554e-12,1.246577e-10,9.418386e-11,6.416386e-11,6
174,3.496229e-11,9.288730e-10,3.519455e-11,3.006231e-10,1.811444e-10,2.881587e-11,1.457973e-10,6
175,7.049422e-11,1.760642e-10,4.634613e-12,7.188252e-12,1.167643e-10,0.000000e+00,2.239539e-11,2
176,7.994828e-11,1.029150e-09,1.927165e-11,1.237623e-10,1.703923e-10,0.000000e+00,1.298539e-10,0

In [21]:
#logistic Regression
from sklearn.linear_model import LogisticRegression
log_reg= LogisticRegression()
log_reg.fit(normalised_train_df , y_balance)

LogisticRegression()

In [22]:
#returns
LogisticRegression(C=1.0 , class_weight=None, dual=False ,fit_intercept=True , intercept_scaling=1 , l1_ratio= None , max_iter=100 ,multi_class='auto' ,n_jobs=None , penalty='50', random_state=None , solver='lbfgs' , tol=0.0001 , verbose=0 , warm_start=False)

LogisticRegression(penalty='50')

In [23]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(log_reg ,normalised_train_df ,y_balance , cv=5, scoring='f1_macro')
print(scores)

[0.51956166 0.56034483 0.43983043 0.50980392 0.58760108]

In [24]:
#Using KFold
from sklearn.model_selection import KFold
from sklearn.metrics import f1_score
kf = KFold(n_splits=5)
f1_scores1=[]

In [25]:
#run for every split
for train_index,test_index in kf.split(normalised_train_df):
    x_train1,x_test1 = normalised_train_df.iloc[train_index],normalised_train_df.iloc[test_index]
    
    y_train1,y_test1 = y_balance[train_index],y_balance[test_index]
    
    model = LogisticRegression().fit(x_train1,y_train1)
    
    #save result to list
    f1_scores1.append(f1_score(y_true=y_test1, y_pred=model.predict(x_test1),pos_label='2A')*100)
f1_scores1

[61.01694915254237, 48.1203007518797, 50.79365079365079, 53.125, 0.0]

In [26]:
#Using StratifiedKFold
from sklearn.model_selection import StratifiedKFold
skf = StratifiedKFold(n_splits=5 ,shuffle=True ,random_state=1)
f1_scores=[]

In [27]:
# Run for every split
for train_index , test_index in skf.split(normalised_train_df , y_balance):
    x_train1 , x_test1 = normalised_train_df.iloc[train_index],normalised_train_df.iloc[test_index]
    
    y_train1 , y_test1 = y_balance[train_index], y_balance[test_index]
    
    model = LogisticRegression().fit(x_train1 , y_train1)
    
    #save result to list
    f1_scores.append(f1_score(y_true=y_test1 , y_pred=model.predict(x_test1), pos_label='2A')*100) 
f1_scores

[58.823529411764696,
 51.48514851485149,
 63.793103448275865,
 60.34482758620688,
 46.464646464646464]

In [38]:
# Using Leave One Out cross validation [LOOCV]
from sklearn.model_selection import LeaveOneOut

loo = LeaveOneOut()

scores = cross_val_score(LogisticRegression(),normalised_train_df , y_balance, cv=loo, scoring='f1_macro')

average_score=scores.mean()*100

In [39]:
 # Using recall,accuracy ,precision and confusion matrix
from sklearn.metrics import recall_score , accuracy_score , precision_score , confusion_matrix

new_pred = log_reg.predict(normalised_test_df)

cnf_mat = confusion_matrix(y_true=y_test, y_pred=new_pred, labels=['2A','3A'])

cnf_mat

array([[37, 45],
       [55, 40]], dtype=int64)

In [40]:
accuracy = accuracy_score(y_true=y_test , y_pred=new_pred)

print('Accuracy:{}' .format(round(accuracy*100),2))

Accuracy:44.0

In [41]:
precision = precision_score(y_true=y_test , y_pred=new_pred , pos_label='2A')

print('Precision:{}'.format(round(precision*100),2))

Precision:40.0

In [42]:
recall = recall_score(y_true=y_test , y_pred=new_pred , pos_label='2A')

print('Recall:{}'.format(round(recall*100),2))

Recall:45.0

In [43]:
f1 = f1_score(y_true=y_test ,y_pred=new_pred, pos_label='2A')

print('F1_score:{}'.format(round(f1*100),2))

F1_score:43.0